[[language]]
name = "latex"

[language-server.texlab.config.texlab.build]
args = [
  "-pdf",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-aux-directory=/tmp",
  "-output-directory=/tmp", # "."
  "%f"
]
onSave = true
auxDirectory = "/tmp"
pdfDirectory = "/tmp"
forwardSearchAfter = true

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
additionalArgs = ["-n3"]

[language-server.texlab.config.texlab.forwardSearch]
executable = "evince-synctex"
args = ["-f", "%l", "%p", "\"texlab -i %f -l %l\""]



[[language]]
name = "markdown"
soft-wrap.wrap-at-text-width = true


[[language]]
name = "txt"
scope = "source.txt"
file-types = ["txt", "text"]
soft-wrap.wrap-at-text-width = true
